### ISSUE TITLE
Guard against checkers never calling back

### ISSUE THREAD

**Issue by nfitch** [joyent/node-checker#27]
If a checker never calls back, it's sitting dead in the water:

```
        var strt = (new Date()).getTime();
        var stats = {};
        check.check(function (err, res) {
                var end = (new Date()).getTime();
                stats.lastChecked = end;
```

So... need an über timeout that wraps the call to check.check.

**Comment by davepacheco** [comment]
This fix explicitly attempts to cover up a failure mode that by construction isn't well understood (namely, there's clearly a bug in the underlying checker).  We now know that this was covering up a bug where requests from the HTTP checker could hang indefinitely if the server returned a response larger than about 16K.  Adding this guard didn't successfully cover up that problem because the checker still leaks a resource each time: namely, a socket from a very small-sized pool.  After hitting the problem 5 times, the result is the same as without this guard: all of this checker's checks for the lifetime of the process will fail after 5 minutes (even if the backend component was never unhealthy), and after that, every check leaks memory until the program crashes.  There are more details in #38.
